# Generated by Django 3.2.9 on 2021-12-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
