# Generated by Django 3.2.9 on 2021-12-27 19:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0009_auto_20211227_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 27, 19, 43, 12, 199029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 27, 19, 43, 12, 199029, tzinfo=utc)),
        ),
    ]
