# Generated by Django 3.2.9 on 2021-12-28 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0010_auto_20211227_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='promote',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 28, 16, 56, 32, 134806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 28, 16, 56, 32, 133809, tzinfo=utc)),
        ),
    ]
