# Generated by Django 3.2.9 on 2022-01-05 08:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0012_auto_20220105_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='child',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='some', to='weblog.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 1, 5, 8, 2, 59, 687639, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='more', to='weblog.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 5, 8, 2, 59, 686644, tzinfo=utc)),
        ),
    ]
