# Generated by Django 3.2.9 on 2022-01-05 08:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0015_auto_20220105_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='child',
            field=models.ManyToManyField(blank=True, null=True, related_name='_weblog_comment_child_+', to='weblog.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2022, 1, 5, 8, 19, 0, 566790, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='more', to='weblog.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 5, 8, 19, 0, 565793, tzinfo=utc)),
        ),
    ]
